"""Central configuration values for Galaxy Runner."""

WINDOW_WIDTH = 1100
WINDOW_HEIGHT = 620
FPS = 60

# Visual perspective setup
HORIZON_Y_RATIO = 0.76
TUNNEL_BOTTOM_Y = 48
TUNNEL_HALF_WIDTH_TOP = 60
TUNNEL_HALF_WIDTH_BOTTOM_RATIO = 0.43

# Player controls
PLAYER_SPEED = 2.8
PLAYER_MAX_OFFSET = 1.0
PLAYER_BASE_Y = 64
PLAYER_WIDTH = 70
PLAYER_HEIGHT = 34

# Obstacles in pseudo-3D depth space
OBSTACLE_DEPTH_START = 0.0
OBSTACLE_DEPTH_END = 1.12
OBSTACLE_SPEED_START = 0.24
OBSTACLE_SPEED_INCREMENT = 0.05
OBSTACLE_SPEED_INCREASE_INTERVAL = 10.0
OBSTACLE_SPAWN_INTERVAL = 0.85
OBSTACLE_BASE_WIDTH = 92
OBSTACLE_BASE_HEIGHT = 34

# Rendering density
STAR_COUNT = 90
GRID_VERTICAL_LINES = 9
GRID_HORIZONTAL_LINES = 11

SCORE_RATE = 22.0
